apiVersion: apps/v1
kind: Deployment
metadata:
  name: notepad-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notepad
  template:
    metadata:
      labels:
        app: notepad
    spec:
      containers:
      - name: notepad
        image: manojgnareddyk/notepad:v1
        ports:
          - containerPort: 5000
