apiVersion: v1
kind: Service
metadata:
  name: notepad-service
spec:
  type: NodePort
  selector:
    app: notepad
  ports:
    - protocol: TCP
      port: 5000         # Service port
      targetPort: 5000   # Flask container port
      nodePort: 30086   # External port you can access
