apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
spec:
  type: NodePort           # change to LoadBalancer if using a cloud provider
  selector:
    app: todoapp
  ports:
    - protocol: TCP
      port: 80             # service port
      targetPort: 80       # container port
      nodePort: 30085     # node port to access externally (30000-32767)